name: Update Gist

on:
  push:
    branch: master

  schedule:
    - cron: "0 16 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update README
        run: node ./index.js
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "grewer@grewer.cn"
          git config --global user.name "grewer"
          git pull
          git add -A
          git commit -m "Updated content" || exit 0
          git push
